### ISSUE TITLE
Histogram label undefined

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#118]
### What feature do you want to see added?

Histogramm label under "Inspect measurements" shows "undefined".

![Unbenannt](https://user-images.githubusercontent.com/90041268/159250835-c89c4c05-71e1-48aa-ad1b-301578dbcbca.PNG)

**Comment by DaGeRe** [comment]
Thanks for the hint. For measurement overview and rca measurement overview, the top left card is empty, since this is the overview histogram and in this cases, we are already at the overview.  This is not nice for the end user, since this is knowledge which is not documented.

For measurement, I completely removed it. For RCA overview, this is not easily possible, since it is the Javascript that decides whether we are in overview or node measurement, but the backend which decides whether a div is present. I'll try to fully fix this.

The current changes are available with https://github.com/jenkinsci/peass-ci-plugin/commit/7c23aecb135c46e537212e9d9dc6df1e096ae95c

**Comment by DaGeRe** [comment]
The `div` is now completely hidden and the layout is fixed: https://github.com/jenkinsci/peass-ci-plugin/commit/21fb27cc09e402873579e7162e223882ee93cb38 Does this work for you?

**Comment by mawHBT** [comment]
Looks fine now.
