### ISSUE TITLE
Clearer "error"-messages if you skip RTS.

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#167]
### What feature do you want to see added?

If you execute a full build, but no significant performance changes were measured, you can keep RTS-results with:
`cleanPerformanceMeasurement cleanRTS: false`
You can increase values for VMs, iterations and so on, repeat the build and check if you find significant performance changes now.
By keeping RTS-results from previous build, RTS is skipped and only measurements are executed with new values. If you do so, you will see error-Messages in Regression Test Selection Log Overview:
`"No Process success runs happened. This indicates an error."`
`"Warning: The regression test selection had an error, and no log files were produced for the current version. No log files where produced for the predecessor. Are there maybe no tests existing or runnable?"`
This is misleading since there is no error, RTS was just skipped. Maybe only the messages should be changed a bit, telling you that this is ok, if you skipped RTS.
The build itself is successful (not unstable like if you had a real error), so this is fine.

**Comment by DaGeRe** [comment]
Thanks for the issue. From my point of view, the problem seems to be that the data are deleted in the first place (and if they are not existing, the error message is ok).
This seems to happen in https://github.com/jenkinsci/peass-ci-plugin/blob/07fd07415acea1cb3e47cd3b582df57389b6b2e2/src/main/java/de/dagere/peass/ci/clean/callables/CleanUtil.java#L17 

Could you try the following

- [ ] Check whether the problem still occurs if the deletion is not done in `CleanUtil`
- [ ] If so: Clean only the other files, but not the files in `logs/dependencyLogs`
- [ ] If not: Check which part of the cleaning causes the problem?

**Comment by DaGeRe** [comment]
The first task is completed. The third task does not make sense anymore.
For completion of the second task, the following should be done:

- [ ] Provide an unit test, that calls `CleanUtil.cleanProjectFolder` (and checks that everything is completed, from a resource folder that is copied to `target` in the unit test).
- [ ] Split `CleanUtil.cleanProjectFolder` into `CleanUtil.cleanProjectFolderRTS` and `CleanUtil.cleanProjectFolderMeasurement`, and do not delete `logs/dependencyLogs` in `CleanUtil.cleanProjectFolderRTS`

**Comment by mawHBT** [comment]
"Provide an unit test, that calls CleanUtil.cleanProjectFolder..." is completed with [f0a12f](https://github.com/jenkinsci/peass-ci-plugin/commit/f0a12f89d8d6fe170e27f2e7004eb90b2c98620c)

**Comment by mawHBT** [comment]
This works now. Setting cleanPerformanceMeasurement cleanRTS: false will not delete the whole projectFolder anymore. So you will get no error-message anymore since RTS-results will remain.
