### ISSUE TITLE
No correct statistics-configuration for measurement overview

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#65]
If I specify a significance of 0.01, changes with t value between 5 and 10 for 2 VM executions are not found. It seems like Peass internally uses a different significance level.

**Comment by DaGeRe** [comment]
Thanks for the hint, this should be fixed in https://github.com/DaGeRe/peass/commit/3d2505778a178d0b376d90325625e8de60eb3350, could you check this?

**Comment by DaGeRe** [comment]
The reason for the still sometimes surprising behavior is, that commons-math implementation of heteroscedatic t-test was used, which normalizes variances. Especially for small sample sizes and differing variances, this leads to big differences in the p-value of the t-test and the t-value. 

Therefore, since https://github.com/DaGeRe/peass/commit/acdca0f078672865bbe5fae6f43e45de90a7c4f4, a homoscedatic t-test is used. Does this work for you?
