### ISSUE TITLE
"Clean Peass-CI Cache" should also work when creating sub-directories

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#82]
### What feature do you want to see added?

If passing a directory in jenkins-pipeline like this:
```
dir('myDir') {
    measure ...
}
```
a folder myDir is created which contains jobName, jobName@tmp und jobName_fullPeass.

If you do so, "_Clean Peass-CI Cache_" does not work anymore, folder workspace/myDir/jobName_fullPeass is not cleaned.

Cleaning folder jobs/jobName/peass-data works as expected because there nothing changes if you pass a directory like above.

**Comment by DaGeRe** [comment]
Thanks for the issue.

Since the `dir` option is able to create arbitrary complex subtrees, it is not possible (with feasible effort) to fix the cleaning for all possible configurations.

Therefore, I provided two options to do this:
- I added the `cleanPerformanceMeasurement` goal which allows you to clean in your pipeline step (and then you can do it in the `dir` block). For testing, it makes sense to clean everything; for production builds, it makes sense to clean measurement and RCA.
- I fixed the CleanAll button, which now cleans the complete folder (regardless of whats contained in it) if it does not find the regular `_fullPeass` folder. Furthermore, I added some information to the clean page. So if you want to clean occasionally, this should work. 

Does this work for you?

**Comment by mawHBT** [comment]
If the step cleanPerformanceMeasurement() is used, all files from previous builds in jenkins_home/workspace/jobName are deleted.
But files in jenkins_home/jobs/jobName/peass-data remain. If full cleaning is intended, peass-data should also be cleaned.

**Comment by mawHBT** [comment]
Works now.
