### ISSUE TITLE
Don't show jenkins credentials in RTS-log

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#90]
### What feature do you want to see added?

If jenkins-configured credentials (username and password) are used in a peass-ci pipeline-build as measure properties, these can be seen in Peass Regression Test Selection Log. ProcessBuilderHelper prints the passed command, which includes user and password in clear text. This must be avoided.

**Comment by DaGeRe** [comment]
Thanks for the issue.

Since I did not find an easy way on my own, I asked in the Jenkins community: https://community.jenkins.io/t/mask-credentials-in-jenkins-plugin/1404 The recommendation is to pass the credentials directly to the plugin.

Therefore, since https://github.com/jenkinsci/peass-ci-plugin/commit/2e45f44d8a53c25d201c73d39e0cfafa4b6b4231, you can additionally specify a credentialsId that will be masked in the logs. You'll have to also define `properties` if you want the credentials to be passed to your gradle process.

Could you check whether this works?

**Comment by bam-hbt** [comment]
I passed the credentials with credentialsId Parameter, and it seems good. (with a warning, "The following steps that have been detected may have insecure interpolation of sensitive variables")
